"use client";import Link from "next/link";import {FormEvent,useState} from "react";import {FormSection} from "./AdminUI";
type Specialty={id:string;nameEn:string};type Doctor=Record<string,unknown>&{id?:string};
function Field({name,label,defaultValue,type="text",rtl=false,span=false,required=true}:{name:string;label:string;defaultValue?:unknown;type?:string;rtl?:boolean;span?:boolean;required?:boolean}){return <label className={`admin-field ${span?"span-2":""}`}>{label}{type==="textarea"?<textarea name={name} defaultValue={String(defaultValue||"")} dir={rtl?"rtl":undefined} required={required}/>:<input name={name} type={type} defaultValue={String(defaultValue||"")} dir={rtl?"rtl":undefined} required={required}/>}</label>}
export function DoctorForm({specialties,doctor}:{specialties:Specialty[];doctor?:Doctor}){const [message,setMessage]=useState("");async function save(e:FormEvent<HTMLFormElement>,draft=false){e.preventDefault();const form=e.currentTarget,f=new FormData(form),body:Record<string,unknown>={id:doctor?.id};for(const [k,v] of f.entries())body[k]=v;body.consultationPrice=Number(f.get("consultationPrice")||0);body.sortOrder=Number(f.get("sortOrder")||0);body.featured=f.get("featured")==="on";body.published=draft?false:f.get("published")==="on";const r=await fetch("/api/admin/doctors",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});setMessage(r.ok?"Doctor profile saved successfully.":"Could not save. Please review the required fields.");if(r.ok&&!doctor)window.location.href="/admin/doctors"}return <form className="admin-form-stack" onSubmit={e=>save(e)}>
<FormSection title="Basic Information" description="Core profile details displayed to patients."><Field name="nameEn" label="English name" defaultValue={doctor?.nameEn}/><Field name="nameAr" label="Arabic name" defaultValue={doctor?.nameAr} rtl/><Field name="titleEn" label="English title" defaultValue={doctor?.titleEn}/><Field name="titleAr" label="Arabic title" defaultValue={doctor?.titleAr} rtl/><label className="admin-field">Specialty<select name="specialtyId" defaultValue={String(doctor?.specialtyId||"")} required><option value="">Select specialty</option>{specialties.map(x=><option key={x.id} value={x.id}>{x.nameEn}</option>)}</select></label><Field name="slug" label="Profile slug" defaultValue={doctor?.slug}/></FormSection>
<FormSection title="Profile Image" description="Use a professional, high-resolution portrait."><div>{doctor?.imageUrl?<img className="admin-image-preview" src={String(doctor.imageUrl)} alt="Current doctor portrait"/>:<div className="admin-image-preview"/>}</div><Field name="imageUrl" label="Image URL" defaultValue={doctor?.imageUrl} required={false}/></FormSection>
<FormSection title="Biography" description="Introduce the doctor in both supported languages."><Field name="shortDescriptionEn" label="English short description" defaultValue={doctor?.shortDescriptionEn} type="textarea"/><Field name="shortDescriptionAr" label="Arabic short description" defaultValue={doctor?.shortDescriptionAr} type="textarea" rtl/><Field name="biographyEn" label="English biography" defaultValue={doctor?.biographyEn} type="textarea"/><Field name="biographyAr" label="Arabic biography" defaultValue={doctor?.biographyAr} type="textarea" rtl/></FormSection>
<FormSection title="Professional Details" description="Credentials, languages, clinic and scheduling information.">{[["qualifications","Qualifications"],["experience","Experience"],["languages","Languages"],["clinic","Clinic"]].flatMap(([n,l])=>[<Field key={n+"En"} name={n+"En"} label={`${l} (English)`} defaultValue={doctor?.[n+"En"]}/>,<Field key={n+"Ar"} name={n+"Ar"} label={`${l} (Arabic)`} defaultValue={doctor?.[n+"Ar"]} rtl/>])}<Field name="consultationPrice" label="Consultation price" type="number" defaultValue={doctor?.consultationPrice} required={false}/><span/><Field name="scheduleEn" label="Working schedule (English)" defaultValue={doctor?.scheduleEn} type="textarea" required={false}/><Field name="scheduleAr" label="Working schedule (Arabic)" defaultValue={doctor?.scheduleAr} type="textarea" rtl required={false}/></FormSection>
<FormSection title="Publishing" description="Control profile visibility and display priority."><label className="admin-check"><input type="checkbox" name="published" defaultChecked={doctor?Boolean(doctor.published):true}/> Published</label><label className="admin-check"><input type="checkbox" name="featured" defaultChecked={Boolean(doctor?.featured)}/> Featured doctor</label><Field name="sortOrder" label="Sort order" type="number" defaultValue={doctor?.sortOrder||0}/></FormSection>
<div className="admin-form-actions"><Link className="admin-secondary" href="/admin/doctors">Cancel</Link><button type="button" className="admin-secondary" onClick={e=>{const form=e.currentTarget.form;if(form){const published=form.elements.namedItem("published") as HTMLInputElement|null;if(published)published.checked=false;form.requestSubmit()}}}>Save as draft</button><button type="submit">Save changes</button></div>{message&&<p role="status" className="success">{message}</p>}</form>}
