import Link from "next/link";
import { db } from "@/lib/db";
import type { Locale } from "@/lib/i18n";
import { BrandLogo } from "./BrandLogo";

export async function Footer({ locale }: { locale: Locale }) {
  const ar = locale === "ar";
  const settings = await db.siteSettings.findUnique({ where: { id: "default" } });
  const socials = [[settings?.facebook, "f", "Facebook"], [settings?.instagram, "◎", "Instagram"], [settings?.linkedin, "in", "LinkedIn"], [settings?.youtube, "▶", "YouTube"]].filter((item): item is [string, string, string] => Boolean(item[0]));
  return <footer className="footer"><div className="container footer-grid"><div className="footer-brand"><BrandLogo locale={locale} logoUrl={settings?.logoUrl} footer /><p>{ar ? "رعاية طبية متخصصة تجمع الخبرة الحديثة والاهتمام الإنساني." : "Considered specialist care, combining modern expertise with genuine human attention."}</p>{socials.length > 0 && <div className="social-links">{socials.map(([url, mark, name]) => <a key={name} href={url} target="_blank" rel="noreferrer" aria-label={name}>{mark}</a>)}</div>}</div><div><strong>{ar ? "استكشف" : "Explore"}</strong><Link href={`/${locale}/doctors`}>{ar ? "الأطباء" : "Doctors"}</Link><Link href={`/${locale}/services`}>{ar ? "الخدمات" : "Services"}</Link><Link href={`/${locale}/about`}>{ar ? "من نحن" : "About"}</Link><Link href={`/${locale}/insurance`}>{ar ? "التأمين" : "Insurance"}</Link></div><div><strong>{ar ? "للمريض" : "Patient"}</strong><Link href={`/${locale}/book-appointment`}>{ar ? "حجز موعد" : "Book appointment"}</Link><Link href={`/${locale}/contact`}>{ar ? "تواصل معنا" : "Contact us"}</Link></div><div className="footer-contact"><strong>{ar ? "تواصل" : "Contact"}</strong>{settings?.phone && <a href={`tel:${settings.phone.replace(/\s/g, "")}`}>{settings.phone}</a>}{settings?.whatsapp && <a href={`https://wa.me/${settings.whatsapp.replace(/\D/g, "")}`}>{ar ? "واتساب: " : "WhatsApp: "}{settings.whatsapp}</a>}{settings?.email && <a href={`mailto:${settings.email}`}>{settings.email}</a>}{(ar ? settings?.addressAr : settings?.addressEn) && <span>{ar ? settings?.addressAr : settings?.addressEn}</span>}{(ar ? settings?.workingHoursAr : settings?.workingHoursEn) && <span>{ar ? settings?.workingHoursAr : settings?.workingHoursEn}</span>}</div></div><div className="container copyright"><span>© {new Date().getFullYear()} {settings?.siteName || "Beit El Teb"}</span><span>{ar ? "رعاية تضعك أولاً" : "Care that puts you first"}</span></div></footer>;
}
