"use client";
import { FormEvent, useState } from "react";
import { FormSection } from "./AdminUI";
type Settings = Record<string, string | null | undefined>;
function Field({ name, label, value, rtl, area, type }: { name: string; label: string; value?: string | null; rtl?: boolean; area?: boolean; type?: string }) { return <label className={`admin-field ${area ? "span-2" : ""}`}>{label}{area ? <textarea name={name} defaultValue={value || ""} dir={rtl ? "rtl" : undefined}/> : <input name={name} type={type} defaultValue={value || ""} dir={rtl ? "rtl" : undefined}/>}</label>; }
export function SettingsForm({ settings: s }: { settings: Settings }) {
 const [saving,setSaving]=useState(false),[feedback,setFeedback]=useState<{ok:boolean;text:string}|null>(null);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setFeedback(null);const body=Object.fromEntries(new FormData(e.currentTarget));try{const r=await fetch("/api/admin/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||"Save failed");setFeedback({ok:true,text:"Settings saved successfully."})}catch(error){setFeedback({ok:false,text:error instanceof Error?error.message:"Could not save settings."})}finally{setSaving(false)}}
 return <form className="admin-form-stack" onSubmit={save}><FormSection title="General" description="Brand identity used throughout the platform."><Field name="siteName" label="Site name" value={s.siteName}/><Field name="logoUrl" label="Logo URL" value={s.logoUrl}/><Field name="faviconUrl" label="Favicon URL" value={s.faviconUrl}/></FormSection><FormSection title="Contact" description="Primary patient communication channels."><Field name="email" label="Email" type="email" value={s.email}/><Field name="phone" label="Phone" value={s.phone}/><Field name="whatsapp" label="WhatsApp" value={s.whatsapp}/></FormSection><FormSection title="Address & Location" description="Clinic address and map destination."><Field name="addressEn" label="English address" value={s.addressEn} area/><Field name="addressAr" label="Arabic address" value={s.addressAr} rtl area/><Field name="googleMapsUrl" label="Google Maps URL" value={s.googleMapsUrl}/></FormSection><FormSection title="Working Hours" description="Opening times displayed to patients."><Field name="workingHoursEn" label="English working hours" value={s.workingHoursEn} area/><Field name="workingHoursAr" label="Arabic working hours" value={s.workingHoursAr} rtl area/></FormSection><FormSection title="Social Media" description="Official social profiles."><Field name="facebook" label="Facebook" value={s.facebook}/><Field name="instagram" label="Instagram" value={s.instagram}/><Field name="linkedin" label="LinkedIn" value={s.linkedin}/><Field name="youtube" label="YouTube" value={s.youtube}/></FormSection><FormSection title="SEO" description="Default metadata for search and sharing."><Field name="seoTitle" label="SEO title" value={s.seoTitle}/><Field name="seoDescription" label="SEO description" value={s.seoDescription} area/><Field name="ogImageUrl" label="Social sharing image URL" value={s.ogImageUrl}/></FormSection><div className="admin-form-actions"><span role="status" className={`admin-feedback ${feedback?.ok?"success":"error"}`}>{feedback?.text}</span><button disabled={saving}>{saving?"Saving…":"Save settings"}</button></div></form>;
}
